/**
 * controllers/authController.js - Zurich Mainnet Authentication Protocol
 * Handles Security Handshakes, Identity Creation, and Referral Linking.
 */

import asyncHandler from 'express-async-handler';
import User from '../models/User.js';
import generateToken from '../utils/generateToken.js';
import sendEmail from '../utils/sendEmail.js';

/**
 * @desc    Authenticate user & get token (Login)
 * @route   POST /api/auth/login
 */
export const authUser = asyncHandler(async (req, res) => {
  const { email, password } = req.body;

  // 1. Find user by email (explicitly select password due to select: false in schema)
  const user = await User.findOne({ email }).select('+password');

  if (!user || !(await user.matchPassword(password))) {
    res.status(401);
    throw new Error('Invalid email or password');
  }

  // 2. Security Check: Prevent login if banned
  if (user.isBanned) {
    res.status(403);
    throw new Error('Access denied. This node has been decommissioned.');
  }

  // 3. Generate JWT
  const token = generateToken(user._id);

  // 4. Set secure httpOnly cookie (Hardened for Production)
  res.cookie('trustra_token', token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production', 
    sameSite: 'strict',
    maxAge: 30 * 24 * 60 * 60 * 1000, // 30 Days
  });

  res.json({
    _id: user._id,
    name: user.name,
    username: user.username,
    email: user.email,
    role: user.role,
    kycStatus: user.kycStatus
  });
});

/**
 * @desc    Register a new user + Referral Protocol
 * @route   POST /api/auth/register
 */
export const registerUser = asyncHandler(async (req, res) => {
  const { name, username, email, password, phone, inviteCode } = req.body;

  // 1. Conflict Check
  const userExists = await User.findOne({ $or: [{ email }, { username }] });
  if (userExists) {
    res.status(400);
    throw new Error('Identity or Email already exists in the Registry');
  }

  // 2. Referral Handshake (B)
  let sponsorId = null;
  if (inviteCode) {
    const sponsor = await User.findOne({ referralCode: inviteCode.toUpperCase() });
    if (sponsor) {
      sponsorId = sponsor._id;
    }
  }

  // 3. Identity Creation
  // Note: referralCode is automatically generated by the User Model default function
  const user = await User.create({
    name: name.trim(),
    username: username.trim().toLowerCase(),
    email: email.trim().toLowerCase(),
    password,
    phone: phone?.trim(),
    referredBy: sponsorId,
    balances: {
      'EUR': 0,
      'ROI': 0,
      'BTC': 0,
      'USDT': 0
    }
  });

  if (user) {
    // Increment sponsor's referral count if applicable
    if (sponsorId) {
      await User.findByIdAndUpdate(sponsorId, { $inc: { referralCount: 1 } });
    }

    const token = generateToken(user._id);

    res.cookie('trustra_token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      maxAge: 30 * 24 * 60 * 60 * 1000,
    });

    res.status(201).json({
      _id: user._id,
      name: user.name,
      username: user.username,
      email: user.email,
      role: user.role,
      referralCode: user.referralCode
    });
  } else {
    res.status(400);
    throw new Error('Invalid user data provided');
  }
});

/**
 * @desc    Get authenticated user's profile
 * @route   GET /api/auth/profile
 */
export const getUserProfile = asyncHandler(async (req, res) => {
  const user = await User.findById(req.user._id).select('-password');

  if (!user) {
    res.status(404);
    throw new Error('User not found');
  }

  // Flatten Map for frontend consumption
  const balances = user.balances instanceof Map 
    ? Object.fromEntries(user.balances) 
    : user.balances;

  res.json({
    ...user.toObject(),
    balances
  });
});

/**
 * @desc    Logout user (Clear Session)
 * @route   POST /api/auth/logout
 */
export const logoutUser = (req, res) => {
  res.clearCookie('trustra_token', {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
  });
  res.status(200).json({ success: true, message: 'Terminal session cleared' });
};

/**
 * @desc    Request password reset OTP
 * @route   POST /api/auth/forgot-password
 */
export const forgotPassword = asyncHandler(async (req, res) => {
  const { email } = req.body;
  const user = await User.findOne({ email });

  if (!user) {
    res.status(404);
    throw new Error('No account found with this email');
  }

  // Generate 6-digit Security Cipher
  const otp = Math.floor(100000 + Math.random() * 900000).toString();
  user.resetPasswordOTP = otp;
  user.resetPasswordExpires = Date.now() + 10 * 60 * 1000; // 10 min expiry
  await user.save();

  try {
    await sendEmail({
      email: user.email,
      subject: 'Trustra Capital: Security Authorization Code',
      message: 'A password reset was requested for your institutional node.',
      otp,
    });

    res.json({ success: true, message: 'Security code dispatched to email' });
  } catch (error) {
    user.resetPasswordOTP = undefined;
    user.resetPasswordExpires = undefined;
    await user.save();
    res.status(500);
    throw new Error('Email dispatch failed. Terminal offline.');
  }
});

/**
 * @desc    Reset password using OTP
 * @route   PUT /api/auth/reset-password
 */
export const resetPassword = asyncHandler(async (req, res) => {
  const { email, otp, newPassword } = req.body;

  const user = await User.findOne({
    email,
    resetPasswordOTP: otp,
    resetPasswordExpires: { $gt: Date.now() },
  });

  if (!user) {
    res.status(400);
    throw new Error('Invalid or expired security code');
  }

  user.password = newPassword;
  user.resetPasswordOTP = undefined;
  user.resetPasswordExpires = undefined;
  await user.save();

  res.json({ success: true, message: 'Password updated. Access restored.' });
});
