/**
 * controllers/authController.js
 * Zurich Mainnet Authentication Protocol
 * Handles user login, registration, profile retrieval, logout, password reset,
 * and referral linking for the Trustra Capital platform.
 */

import asyncHandler from 'express-async-handler';
import User from '../models/User.js';
import generateToken from '../utils/generateToken.js';
import sendEmail from '../utils/sendEmail.js';

/**
 * @desc    Authenticate user and establish session via secure httpOnly cookie
 * @route   POST /api/auth/login
 * @access  Public
 */
export const authUser = asyncHandler(async (req, res) => {
  // Extract login credentials from request body
  const { email, password } = req.body;

  // Step 1: Find user by email and include password field (excluded by default)
  const user = await User.findOne({ email }).select('+password');

  // Step 2: Validate credentials – check if user exists and password matches
  if (!user || !(await user.matchPassword(password))) {
    res.status(401);
    throw new Error('Invalid email or password');
  }

  // Step 3: Security check – prevent login if user account is banned
  if (user.isBanned) {
    res.status(403);
    throw new Error('Access denied. This node has been decommissioned.');
  }

  // Step 4: Generate JWT token for session identification
  const token = generateToken(user._id);

  // Step 5: Set secure httpOnly cookie containing the token
  const isDev = process.env.NODE_ENV !== 'production';
  res.cookie('trustra_token', token, {
    httpOnly: true,
    secure: !isDev,                    // false in dev (localhost is HTTP), true in production
    sameSite: 'strict',
    maxAge: 30 * 24 * 60 * 60 * 1000,  // 30 days expiration
  });

  // Step 6: Return consistent shape that frontend expects
  res.json({
    success: true,
    user: {
      _id: user._id,
      name: user.name,
      username: user.username,
      email: user.email,
      role: user.role,
      kycStatus: user.kycStatus,
    }
  });
});

/**
 * @desc    Register a new user and optionally link to a referrer via invite code
 * @route   POST /api/auth/register
 * @access  Public
 */
export const registerUser = asyncHandler(async (req, res) => {
  // Extract registration data from request body
  const { name, username, email, password, phone, inviteCode } = req.body;

  // Step 1: Check for existing user by email or username (prevent duplicates)
  const userExists = await User.findOne({
    $or: [{ email }, { username }],
  });

  if (userExists) {
    res.status(400);
    throw new Error('Identity or Email already exists in the Registry');
  }

  // Step 2: Process referral/invite code if provided
  let sponsorId = null;
  if (inviteCode) {
    const sponsor = await User.findOne({ referralCode: inviteCode.toUpperCase() });
    if (sponsor) {
      sponsorId = sponsor._id;
    }
  }

  // Step 3: Create new user document
  // Note: referralCode is automatically generated by User model pre-save hook
  const user = await User.create({
    name: name.trim(),
    username: username.trim().toLowerCase(),
    email: email.trim().toLowerCase(),
    password,                          // Will be hashed by pre-save middleware
    phone: phone?.trim(),
    referredBy: sponsorId,
    balances: {
      EUR: 0,
      ROI: 0,
      BTC: 0,
      USDT: 0,
    },
  });

  if (user) {
    // Step 4: Increment referral count for sponsor (if referral was valid)
    if (sponsorId) {
      await User.findByIdAndUpdate(sponsorId, { $inc: { referralCount: 1 } });
    }

    // Step 5: Generate session token
    const token = generateToken(user._id);

    // Step 6: Set secure httpOnly cookie
    const isDev = process.env.NODE_ENV !== 'production';
    res.cookie('trustra_token', token, {
      httpOnly: true,
      secure: !isDev,
      sameSite: 'strict',
      maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days
    });

    // Step 7: Return new user profile (no token in body – cookie is used)
    res.status(201).json({
      success: true,
      user: {
        _id: user._id,
        name: user.name,
        username: user.username,
        email: user.email,
        role: user.role,
        referralCode: user.referralCode,
      }
    });
  } else {
    res.status(400);
    throw new Error('Invalid user data provided');
  }
});

/**
 * @desc    Retrieve profile of currently authenticated user
 * @route   GET /api/auth/profile
 * @access  Private (requires valid auth cookie)
 */
export const getUserProfile = asyncHandler(async (req, res) => {
  // req.user is populated by auth middleware (from cookie JWT)
  const user = await User.findById(req.user._id).select('-password');

  if (!user) {
    res.status(404);
    throw new Error('User not found');
  }

  // Convert balances Map to plain JavaScript object for frontend
  const balances = user.balances instanceof Map
    ? Object.fromEntries(user.balances)
    : user.balances;

  // Return full user object with flattened balances
  res.json({
    success: true,
    user: {
      ...user.toObject(),
      balances,
    }
  });
});

/**
 * @desc    Logout user by clearing authentication cookie
 * @route   POST /api/auth/logout
 * @access  Public (clears cookie regardless of auth)
 */
export const logoutUser = (req, res) => {
  // Clear the httpOnly auth cookie
  res.clearCookie('trustra_token', {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
  });

  // Respond with success message
  res.status(200).json({
    success: true,
    message: 'Terminal session cleared',
  });
};

/**
 * @desc    Request password reset OTP via email
 * @route   POST /api/auth/forgot-password
 * @access  Public
 */
export const forgotPassword = asyncHandler(async (req, res) => {
  // Extract email from request body
  const { email } = req.body;

  // Find user by email
  const user = await User.findOne({ email });

  if (!user) {
    res.status(404);
    throw new Error('No account found with this email');
  }

  // Generate 6-digit one-time password (OTP)
  const otp = Math.floor(100000 + Math.random() * 900000).toString();

  // Store OTP and set 10-minute expiry
  user.resetPasswordOTP = otp;
  user.resetPasswordExpires = Date.now() + 10 * 60 * 1000;

  await user.save();

  try {
    // Send OTP email to user
    await sendEmail({
      email: user.email,
      subject: 'Trustra Capital: Security Authorization Code',
      message: 'A password reset was requested for your institutional node.',
      otp,
    });

    res.json({
      success: true,
      message: 'Security code dispatched to email',
    });
  } catch (error) {
    // Clear OTP fields if email fails
    user.resetPasswordOTP = undefined;
    user.resetPasswordExpires = undefined;
    await user.save();

    res.status(500);
    throw new Error('Email dispatch failed. Terminal offline.');
  }
});

/**
 * @desc    Reset password using valid OTP
 * @route   PUT /api/auth/reset-password
 * @access  Public
 */
export const resetPassword = asyncHandler(async (req, res) => {
  // Extract reset data from request body
  const { email, otp, newPassword } = req.body;

  // Find user with matching email, OTP, and non-expired code
  const user = await User.findOne({
    email,
    resetPasswordOTP: otp,
    resetPasswordExpires: { $gt: Date.now() },
  });

  if (!user) {
    res.status(400);
    throw new Error('Invalid or expired security code');
  }

  // Update password (will be hashed by pre-save middleware)
  user.password = newPassword;

  // Clear OTP fields after successful reset
  user.resetPasswordOTP = undefined;
  user.resetPasswordExpires = undefined;

  await user.save();

  res.json({
    success: true,
    message: 'Password updated. Access restored.',
  });
});
