services:
  - type: web
    name: trustra-capital-trade
    runtime: node
    plan: free
    region: ohio
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SOCKET_CORS_ORIGIN
        value: https://trustra-capital-trade.vercel.app
      - key: FRONTEND_URL
        value: https://trustra-capital-trade.vercel.app
      - key: VITE_API_URL
        value: https://trustracapitaltrade-backend.onrender.com/api

databases:
  - name: trustra-db
    plan: free
    region: ohio
