// src/pages/Dashboard/ReferralDashboard.jsx
import React, { useState } from 'react';
import { Copy, Users, TrendingUp, Gift, CheckCircle2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../../context/AuthContext';

export default function ReferralDashboard() {
  const { user } = useAuth();
  const [copied, setCopied] = useState(false);

  // Zurich-Mainnet referral link generation
  const referralLink = `${window.location.origin}/register?invite=${user?.referralCode}`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(referralLink);
    setCopied(true);
    toast.success("Referral Link synchronized to clipboard.");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-8 space-y-10 animate-in fade-in duration-700 max-w-6xl mx-auto">
      <header>
        <h1 className="text-4xl font-black italic uppercase tracking-tighter text-white">
          Node <span className="text-yellow-500 not-italic">Expansion</span>
        </h1>
        <p className="text-gray-500 text-[10px] font-mono uppercase tracking-[0.4em] mt-2 italic">
          Affiliate Protocol • Network Growth Logic
        </p>
      </header>

      {/* STATS GRID */}
      <div className="grid md:grid-cols-3 gap-6">
        <div className="bg-[#0A0C10] border border-white/5 p-8 rounded-[2.5rem] flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black uppercase text-gray-500 tracking-widest mb-1">Active Referrals</p>
            <h3 className="text-3xl font-black italic text-white">{user?.referralCount || 0}</h3>
          </div>
          <Users className="text-yellow-500/20" size={40} />
        </div>

        <div className="bg-[#0A0C10] border border-white/5 p-8 rounded-[2.5rem] flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black uppercase text-gray-500 tracking-widest mb-1">Commission Rate</p>
            <h3 className="text-3xl font-black italic text-white">10%</h3>
          </div>
          <TrendingUp className="text-yellow-500/20" size={40} />
        </div>

        <div className="bg-[#0A0C10] border border-white/5 p-8 rounded-[2.5rem] flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black uppercase text-gray-500 tracking-widest mb-1">Total Earnings</p>
            <h3 className="text-3xl font-black italic text-yellow-500">
              €{(user?.referralEarnings || 0).toFixed(2)}
            </h3>
          </div>
          <Gift className="text-yellow-500/20" size={40} />
        </div>
      </div>

      {/* REFERRAL LINK SECTION */}
      <div className="bg-white/[0.02] border border-white/5 rounded-[3rem] p-10 flex flex-col items-center text-center space-y-6">
        <div className="bg-yellow-500/10 p-4 rounded-full text-yellow-500">
          <Gift size={32} />
        </div>
        <div>
          <h2 className="text-xl font-black uppercase italic text-white">Share Your Network Key</h2>
          <p className="text-gray-500 text-xs mt-2 max-w-sm">
            Earn 10% of the daily yield generated by every node that registers using your unique authorization code.
          </p>
        </div>

        <div className="w-full max-w-xl flex items-center gap-2 bg-black border border-white/10 p-2 rounded-2xl group focus-within:border-yellow-500/50 transition-all">
          <input 
            type="text" 
            readOnly 
            value={referralLink} 
            className="flex-1 bg-transparent border-none text-[11px] font-mono text-gray-400 px-4 outline-none"
          />
          <button 
            onClick={copyToClipboard}
            className="bg-yellow-500 text-black p-3 rounded-xl hover:bg-white transition-all active:scale-95"
          >
            {copied ? <CheckCircle2 size={18} /> : <Copy size={18} />}
          </button>
        </div>
      </div>
    </div>
  );
}
