// src/pages/InvestConfirm.jsx - Production v8.4.1
import React, { useState } from 'react';                                   import { useLocation, useNavigate } from 'react-router-dom';
import { ShieldCheck, Lock, Loader2, ArrowRight, Shield } from 'lucide-react';
import api from '../api/api';                                              import { API_ENDPOINTS } from '../constants/api';                          import toast from 'react-hot-toast';
                                                                           export default function InvestConfirm() {                                    const { state } = useLocation();
  const navigate = useNavigate();                                            const [isDeploying, setIsDeploying] = useState(false);                   
  // Guard clause: Ensure user didn't refresh or navigate here manually      if (!state?.planKey || !state?.amount) {                                     // We use a slight delay or useEffect for navigation in real apps,
    // but a direct return works for this logic flow.                          if (typeof window !== 'undefined') navigate('/plans');                     return null;
  }                                                                                                                                                     const handleFinalize = async () => {
    setIsDeploying(true);                                                      try {                                                                        await api.post(API_ENDPOINTS.INVESTMENT.CREATE, {
        planKey: state.planKey,
        amount: state.amount
      });
                                                                                 toast.success("Node Deployed Successfully", {                                icon: '🚀',
        style: { background: '#0a0c10', color: '#fff', border: '1px solid #eab308' }
      });                                                                                                                                                   // Redirect to the logs to see the active investment
      navigate('/investments');
    } catch (err) {                                                              toast.error(err.response?.data?.message || "Deployment Failed");         } finally {
      setIsDeploying(false);                                                   }                                                                        };                                                                                                                                                    return (                                                                     <div className="min-h-screen bg-[#020617] text-white flex items-center justify-center p-6 selection:bg-yellow-500/30">
      <div className="max-w-md w-full bg-[#0a0c10] border border-white/10 rounded-[3.5rem] p-10 text-center shadow-3xl relative overflow-hidden">
        {/* Decorative background element */}
        <div className="absolute -top-24 -left-24 w-48 h-48 bg-yellow-500/5 blur-[80px] rounded-full" />

        <div className="w-20 h-20 bg-yellow-500/10 rounded-full flex items-center justify-center mx-auto mb-8 relative">                                        <ShieldCheck className="text-yellow-500" size={40} />                      <div className="absolute inset-0 border-2 border-yellow-500/20 rounded-full animate-ping" />                                                        </div>                                                                                                                                                <h2 className="text-2xl font-black uppercase italic tracking-tighter mb-2">Audit Confirmation</h2>
        <p className="text-gray-500 text-[10px] font-black uppercase tracking-[0.3em] mb-10">Verification Protocol v8.4.1</p>                         
        <div className="space-y-1 bg-white/[0.02] rounded-3xl border border-white/5 mb-10 overflow-hidden">                                                     <div className="flex justify-between p-5 border-b border-white/5">                                                                                      <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Protocol Tier</span>                                                 <span className="text-sm font-black uppercase italic text-yellow-500">
              {state.planKey.replace('starter', 'Rio Starter').replace('basic', 'Rio Basic').replace('standard', 'Rio Standard').replace('advanced', 'Rio Advanced').replace('elite', 'Rio Elite')}                                          </span>                                                                  </div>                                                                     <div className="flex justify-between p-5 border-b border-white/5">                                                                                      <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Principal Allocation</span>                                          <span className="text-sm font-black text-white">€{state.amount.toLocaleString('de-DE', { minimumFractionDigits: 2 })}</span>                        </div>
          <div className="flex justify-between p-5">                                   <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Gas/Network Fee</span>                                               <span className="text-[10px] font-black text-emerald-500 uppercase">Waived (Trustra)</span>
          </div>                                                                   </div>                                                                                                                                                <button                                                                      onClick={handleFinalize}
          disabled={isDeploying}                                                     className="w-full py-5 bg-yellow-500 hover:bg-white text-black font-black rounded-2xl uppercase tracking-[0.2em] text-xs flex items-center justify-center gap-3 transition-all active:scale-95 disabled:opacity-50 shadow-xl shadow-yellow-500/10"                                                        >                                                                            {isDeploying ? (                                                             <>                                                                           <Loader2 className="animate-spin" size={18} />                             <span>Syncing Ledger...</span>
            </>                                                                      ) : (
            <>                                                                           <Lock size={16} />
              EXECUTE DEPLOYMENT
            </>                                                                      )}                                                                       </button>                                                                                                                                             <div className="mt-8 flex items-center gap-3 justify-center opacity-40">                                                                                 <Shield size={12} />                                                       <p className="text-[9px] text-gray-400 uppercase font-black tracking-[0.2em]">
             End-to-End Encrypted Session
           </p>
        </div>                                                                   </div>                                                                   </div>                                                                   );                                                                       }
